Update .gitattributes
schmittjoh/php-option pull request #66
Opened 2022-06-28 20:58 UTC by erikn69

2022-06-28 22:27 UTC, GrahamCampbell commented
Thanks for the PR. Can you put this in the file, alphabetically, please?

2022-06-28 22:45 UTC, GrahamCampbell requested changes

2022-06-28 22:45 UTC, GrahamCampbell commented on .gitattributes
> +/tests export-ignore
Please leave tests alone. I did directories first, alphabetically, then files, alphabetically.

2022-06-28 22:56 UTC, erikn69 commented on .gitattributes
> +/tests export-ignore
Done

2022-06-29 07:28 UTC, merged

2022-06-29 07:28 UTC, GrahamCampbell commented
Thanks.